version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=tickets
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
  crawler:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    env_file:
      - ./dev.env
    volumes:
      - /app/node_modules
      - .:/app
volumes:
  pgdata:
