version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=tickets
      - POSTGRES_PASSWORD=password
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    env_file:
      - ./api/dev.env
    volumes:
      - /app/node_modules
      - ./api:/app
  client:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./client:/app
